# Generated by Django 4.2.6 on 2023-10-30 08:11

import core.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique_for_date='start_date')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('description', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('CO', 'Соревнования'), ('TC', 'Тренировочные сборы'), ('SE', 'Семинар')], max_length=2)),
                ('participation_type', models.CharField(choices=[('IN', 'Индивидуальные'), ('TE', 'Командные или эстафетные')], max_length=2)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('sport_kind', models.CharField(choices=[('ORI', 'Ориентирование'), ('ROG', 'Рогейн'), ('RUN', 'Бег, трейл, скайраннинг, ходьба'), ('ADV', 'Гонки приключенческие, с препятствиями'), ('ALP', 'Туризм, скалолазание, альпинизм'), ('BYC', 'Велоспорт'), ('SKI', 'Лыжные гонки, лыжероллеры'), ('MULT', 'Триатлон, дуатлон, swimrun'), ('SWIM', 'Плавание'), ('OTH', 'Прочее')], max_length=4)),
                ('scale', models.CharField(choices=[('TR', 'Тренировочные'), ('LOC', 'Локальные'), ('REG', 'Региональные'), ('IREG', 'Межрегиональные (зональные)'), ('NAT', 'Национальные'), ('INT', 'Международные')], max_length=4)),
                ('logo', models.ImageField(upload_to='event_logos')),
                ('publication_status', models.CharField(choices=[('DR', 'Черновик'), ('PUB', 'Опубликовано'), ('NS', 'Не показывать в календаре')], max_length=3)),
                ('city_or_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cityordistrict')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
                ('user', models.ForeignKey(on_delete=models.SET(core.services.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
