# Generated by Django 4.2.6 on 2023-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(),
        ),
    ]
