# Generated by Django 4.2.6 on 2023-11-03 12:58

import core.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_date_end_alter_event_date_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('third_name', models.CharField(blank=True, max_length=25, null=True)),
                ('qualification', models.CharField(choices=[('IMS', 'МСМК'), ('MS', 'МС'), ('CMS', 'КМС'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('I-Y', 'Iю'), ('II-Y', 'IIю'), ('III-Y', 'IIIю'), ('NQ', 'б/р')], max_length=5)),
                ('gender', models.CharField(choices=[('M', 'мужской'), ('W', 'женский')], max_length=1)),
                ('birth_date', models.DateField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_team', models.BooleanField()),
                ('team_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен соответствовать формату '+999999999' и может содержать до 15 цифр", regex='^\\+?1?\\d{9,15}$')])),
                ('city_or_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cityordistrict')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
                ('user', models.ForeignKey(on_delete=models.SET(core.services.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
